Repository Azure/aml-run, pull requests merged in 2020-05, with the labels that each got.

#19 Added input validation & unit tests
  .github/workflows/python.yml
  .gitignore
  Dockerfile
  README.md
  code/entrypoint.sh
  code/main.py
  code/schemas.py
  code/utils.py
  tests/objects.py
  tests/test_main.py
  tests/test_utils.py
Labels: enhancement

#21 Ashishonce/integration tests
  .cloud/.azure/test/test_aks_compute.json
  .cloud/.azure/test/test_aml_compute.json
  .cloud/.azure/test/test_workspace.json
  .cloud/.azure/test/train_withConfigpy.json
  .cloud/.azure/test/train_withYamlRunConfig.json
  .github/workflows/integration.yml
  tests/test_data/train_with_configpy/environment.yml
  tests/test_data/train_with_configpy/run_config.py
  tests/test_data/train_with_configpy/train.py
  tests/test_data/train_with_yamlConfig/environment.yml
  tests/test_data/train_with_yamlConfig/run_config.yml
  tests/test_data/train_with_yamlConfig/train.py
Labels: enhancement

#24 Added artifact download
  .cloud/.azure/run.json
  .cloud/.azure/test/train_withConfigpy.json
  .cloud/.azure/test/train_with_python_config.json
  .cloud/.azure/test/train_with_yaml_run_config.json
  .github/workflows/integration.yml
  README.md
  action.yml
  code/main.py
  code/schemas.py
  tests/train/train_with_python_config/environment.yml
  tests/train/train_with_python_config/run_config.py
  tests/train/train_with_python_config/train.py
  tests/train/train_with_yaml_run_config/environment.yml
  tests/train/train_with_yaml_run_config/run_config.yml
  tests/train/train_with_yaml_run_config/train.py
Labels: enhancement

#26 Updating ReadMe
  README.md
Labels: documentation

#28 Update azureml-sdk to 1.5.0
  Dockerfile
Labels: enhancement

#29 Remove ls
  .gitattributes
  CODE_OF_CONDUCT.md
  LICENSE
  SECURITY.md
  code/entrypoint.sh
Labels: bug

#30 removed markdown conversion
  README.md
  code/main.py
Labels: bug

#34 Upgrade to Azure ML SDK 1.6.0
  Dockerfile
Labels: enhancement
